/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.legacymoddingmc.mappinggenerator;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/**
 * A simple unit test for the 'io.legacymoddingmc.mappinggenerator.greeting' plugin.
 */
class MappingGeneratorPluginTest {
    @Test void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("io.legacymoddingmc.mappinggenerator.greeting");

        // Verify the result
        assertNotNull(project.getTasks().findByName("greeting"));
    }
}
